language: python
python:
  - 3.6
install:
  - pip install numpy
  - pip install matplotlib
  - pip install chainer
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python -m unittest discover tests